spring:
  cloud:
    gateway:
      routes:
        - id: profilesPrincipal
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/me
            - Method=GET,PUT,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: PublicSearch
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles
            - Query=projection, public-search-profile
            - Query=isOpenForWork, true
        - id: AdminSearch
          uri: http://api-gateway
          predicates:
            - Path=/api/v1/profiles
            - Query=projection, admin-search-profile
            - Query=isOpenForWork, true
          filters:
            - RewritePath=/api/v1/profiles/(?<path>.*), /api/v1/profiles/admin/search//$\{path}
        - id: GeneralSearchDeny
          uri: no://op
          predicates:
            - Path=/api/v1/profiles/search/**
          filters:
            - SetStatus=403
        - id: profiles
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/*/*, /api/v1/description/**, /api/v1/profiles/api-doc, /api/v1/count/**
        - id: multimedia
          uri: http://multimedia-manager
          predicates:
            - Path=/api/v1/multimedia, /api/v1/multimedia/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
        - id: adminSearchDownstream
          uri: http://profiles
          predicates:
            - Path=/api/v1/profiles/admin/search/**
          metadata:
            auth-roles:
              - iamai-admin
          filters:
            - RewritePath=/api/v1/profiles/admin/search/(?<path>.*), /api/v1/profiles//$\{path}
keycloak-client:
  server-url: https://auth-dev.agenadev.com/auth
